### ISSUE TITLE
来自学弟的感谢

### ISSUE THREAD

**Issue by ycfung** [YouthLin/Library-with-JSF-EJB-JPA#1]
网课上的云里雾里，感谢学长提供了思路（这题目真就四年不换

**Comment by youthlin** [comment]
@ycfung 这个课应付考试就行了，千万不要花太多时间在 EJB 这边，没有哪家公司面试还问 EJB 的，多实践下 Spring 全家桶更有帮助哈。

**Comment by ycfung** [comment]
好的，谢谢学长！！
